function [L_new,R_new,O_new,S_new,A_new]=bar_update(R,L,O,S,A,p,E_L,E_R,dt)
n=size(L.T,1);
cir_mat=repmat(1:n,n,1);
x=abs(cir_mat'-cir_mat);
I_L=[sum(O.I_L,2) sum(O.I_L,2)];
I_R=[sum(O.I_R,2) sum(O.I_R,2)];
P_R=max(E_R-p.gI*exp(-x.^5/p.sigma^5)*I_R+p.g1*(R.T'*exp(-x.^5/(2*p.sigma)^5))'+p.g0*(L.T'*exp(-x.^5/(2*p.sigma)^5))' ,0).*(1+p.omiga*exp(-x.^5/p.sigma^5)*A);
P_L=max(E_L-p.gI*exp(-x.^5/p.sigma^5)*I_L+p.g2*(L.T'*exp(-x.^5/(2*p.sigma)^5))'+p.g0*(R.T'*exp(-x.^5/(2*p.sigma)^5))' ,0).*(1+p.omiga*exp(-x.^5/p.sigma^5)*A);
P_normalize=sum([P_R.^2 P_L.^2],2);
L_new.T=L.T+1/p.tau*(-L.T+100*P_L.^2./((10+L.H).^2+repmat(P_normalize,1,2)))*dt;
L_new.H=L.H+1/p.tau_H*(-L.H+2*L.T)*dt;
R_new.T=R.T+1/p.tau*(-R.T+100*P_R.^2./((10+R.H).^2+repmat(P_normalize,1,2)))*dt;
R_new.H=R.H+1/p.tau_H*(-R.H+2*R.T)*dt;
S_new.T=S.T+1/p.tau*( -S.T+100*(R.T+L.T).^2./((10+S.H).^2+repmat( sum((R.T+L.T).^2,2) ,1,2)) )*dt;
S_new.H=S.H+1/p.tau_H*(-S.H+S.T)*dt;
O_normalize=sum([max((R.T-L.T),0).^2 max((L.T-R.T),0).^2] ,2);
O_new.I_L=O.I_L+1/p.tau_I*(-O.I_L+30*max((R.T-L.T),0).^2./(p.alpha^2+repmat(O_normalize,1,2)))*dt;
O_new.I_R=O.I_R+1/p.tau_I*(-O.I_R+30*max((L.T-R.T),0).^2./(p.alpha^2+repmat(O_normalize,1,2)))*dt;
Dif=[S.T(:,1)-S.T(:,2) S.T(:,2)-S.T(:,1)];
A_new=A+1/p.tau_A*(-A+( sign(Dif).*(Dif.^2) )./(repmat(sum(Dif.^2,2),1,2)+p.alpha_A^2))*dt;
end
